export interface HandbookCommand {
  id: string;
  title: string;
  description: string;
  command: string;
  category: string;
  lessonSlug: string;
  lessonTitle: string;
}

// Auto-generated by scripts/extract-commands.js — do not hand-edit.
// Re-run `node scripts/extract-commands.js` after editing any lesson's
// command list, then copy src/data/commands.json's contents here if you
// want it version-controlled as TS instead of JSON.
export const commands: HandbookCommand[] = [
  {
    "id": "basics-update-upgrade",
    "title": "Update & Upgrade",
    "description": "Update package lists and upgrade all installed packages to latest versions",
    "command": "pkg update && pkg upgrade",
    "category": "Package Management",
    "lessonSlug": "/Basics",
    "lessonTitle": "Basics"
  },
  {
    "id": "basics-install-a-package",
    "title": "Install a Package",
    "description": "Install any package from Termux repositories",
    "command": "pkg install <package-name>",
    "category": "Package Management",
    "lessonSlug": "/Basics",
    "lessonTitle": "Basics"
  },
  {
    "id": "basics-list-files",
    "title": "List Files",
    "description": "List all files and folders in the current directory",
    "command": "ls",
    "category": "Files & Directories",
    "lessonSlug": "/Basics",
    "lessonTitle": "Basics"
  },
  {
    "id": "basics-change-directory",
    "title": "Change Directory",
    "description": "Navigate into a folder or directory",
    "command": "cd <folder>",
    "category": "Files & Directories",
    "lessonSlug": "/Basics",
    "lessonTitle": "Basics"
  },
  {
    "id": "basics-go-back-a-directory",
    "title": "Go Back a Directory",
    "description": "Move up one level in the directory hierarchy",
    "command": "cd ..",
    "category": "Files & Directories",
    "lessonSlug": "/Basics",
    "lessonTitle": "Basics"
  },
  {
    "id": "basics-create-directory",
    "title": "Create Directory",
    "description": "Create a new folder",
    "command": "mkdir <folder>",
    "category": "Files & Directories",
    "lessonSlug": "/Basics",
    "lessonTitle": "Basics"
  },
  {
    "id": "basics-create-empty-file",
    "title": "Create Empty File",
    "description": "Create a blank file quickly",
    "command": "touch <filename>",
    "category": "Files & Directories",
    "lessonSlug": "/Basics",
    "lessonTitle": "Basics"
  },
  {
    "id": "basics-view-file-contents",
    "title": "View File Contents",
    "description": "Display the complete contents of a text file",
    "command": "cat <file>",
    "category": "Files & Directories",
    "lessonSlug": "/Basics",
    "lessonTitle": "Basics"
  },
  {
    "id": "basics-move-or-rename-file",
    "title": "Move or Rename File",
    "description": "Move a file to another location or rename it",
    "command": "mv <source> <destination>",
    "category": "Files & Directories",
    "lessonSlug": "/Basics",
    "lessonTitle": "Basics"
  },
  {
    "id": "basics-copy-file",
    "title": "Copy File",
    "description": "Create a duplicate of a file",
    "command": "cp <source> <destination>",
    "category": "Files & Directories",
    "lessonSlug": "/Basics",
    "lessonTitle": "Basics"
  },
  {
    "id": "basics-delete-file",
    "title": "Delete File",
    "description": "Permanently remove a file",
    "command": "rm <file>",
    "category": "Files & Directories",
    "lessonSlug": "/Basics",
    "lessonTitle": "Basics"
  },
  {
    "id": "basics-delete-directory",
    "title": "Delete Directory",
    "description": "Remove a directory and all its contents recursively",
    "command": "rm -rf <folder>",
    "category": "Files & Directories",
    "lessonSlug": "/Basics",
    "lessonTitle": "Basics"
  },
  {
    "id": "basics-open-nano-editor",
    "title": "Open Nano Editor",
    "description": "Edit text files using the Nano text editor",
    "command": "nano <file>",
    "category": "Text Editing",
    "lessonSlug": "/Basics",
    "lessonTitle": "Basics"
  },
  {
    "id": "basics-clear-terminal",
    "title": "Clear Terminal",
    "description": "Clear the terminal screen and remove all text",
    "command": "clear",
    "category": "Utilities",
    "lessonSlug": "/Basics",
    "lessonTitle": "Basics"
  },
  {
    "id": "basics-help",
    "title": "Help",
    "description": "View detailed help and options for any command",
    "command": "<command> --help",
    "category": "Utilities",
    "lessonSlug": "/Basics",
    "lessonTitle": "Basics"
  },
  {
    "id": "lesson1-update-packages",
    "title": "Update Packages",
    "description": "Updates the package lists for upgrades and installs",
    "command": "pkg update",
    "category": "Package Management",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-upgrade-packages",
    "title": "Upgrade Packages",
    "description": "Upgrades all installed packages to their latest version",
    "command": "pkg upgrade",
    "category": "Package Management",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-install-package",
    "title": "Install Package",
    "description": "Installs a package",
    "command": "pkg install [package_name]",
    "category": "Package Management",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-uninstall-package",
    "title": "Uninstall Package",
    "description": "Uninstalls a package",
    "command": "pkg uninstall [package_name]",
    "category": "Package Management",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-search-packages",
    "title": "Search Packages",
    "description": "Searches for packages containing the keyword",
    "command": "pkg search [keyword]",
    "category": "Package Management",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-list-all-packages",
    "title": "List All Packages",
    "description": "Lists all available packages",
    "command": "pkg list-all",
    "category": "Package Management",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-package-info",
    "title": "Package Info",
    "description": "Displays information about a package",
    "command": "pkg info [package_name]",
    "category": "Package Management",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-list-installed-packages",
    "title": "List Installed Packages",
    "description": "Lists all installed packages",
    "command": "pkg list-installed",
    "category": "Package Management",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-setup-storage",
    "title": "Setup Storage",
    "description": "Sets up storage access for Termux",
    "command": "termux-setup-storage",
    "category": "File & Storage",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-open-file-or-directory",
    "title": "Open File or Directory",
    "description": "Opens a file or directory with default app",
    "command": "termux-open [file/path]",
    "category": "File & Storage",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-open-url",
    "title": "Open URL",
    "description": "Opens the URL in default browser",
    "command": "termux-open-url [URL]",
    "category": "File & Storage",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-share-content",
    "title": "Share Content",
    "description": "Shares files or text using Android share menu",
    "command": "termux-share",
    "category": "File & Storage",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-list-storage-volumes",
    "title": "List Storage Volumes",
    "description": "Lists all available storage volumes",
    "command": "termux-storage-list",
    "category": "File & Storage",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-get-storage-info",
    "title": "Get Storage Info",
    "description": "Gets storage info about a path",
    "command": "termux-storage-get [path]",
    "category": "File & Storage",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-show-toast-message",
    "title": "Show Toast Message",
    "description": "Shows a toast message",
    "command": "termux-toast [message]",
    "category": "System & Notification",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-send-notification",
    "title": "Send Notification",
    "description": "Sends a system notification",
    "command": "termux-notification",
    "category": "System & Notification",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-vibrate-device",
    "title": "Vibrate Device",
    "description": "Vibrates the device",
    "command": "termux-vibrate",
    "category": "System & Notification",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-keep-device-awake",
    "title": "Keep Device Awake",
    "description": "Keeps device awake",
    "command": "termux-wake-lock",
    "category": "System & Notification",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-allow-sleep",
    "title": "Allow Sleep",
    "description": "Allows device to sleep",
    "command": "termux-wake-unlock",
    "category": "System & Notification",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-get-clipboard",
    "title": "Get Clipboard",
    "description": "Gets contents of clipboard",
    "command": "termux-clipboard-get",
    "category": "Clipboard",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-set-clipboard",
    "title": "Set Clipboard",
    "description": "Sets clipboard contents",
    "command": "termux-clipboard-set [text]",
    "category": "Clipboard",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-take-photo",
    "title": "Take Photo",
    "description": "Takes a photo and saves it",
    "command": "termux-camera-photo [output_file]",
    "category": "Camera & Media",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-record-video",
    "title": "Record Video",
    "description": "Records a video and saves it",
    "command": "termux-camera-record [output_file]",
    "category": "Camera & Media",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-play-media",
    "title": "Play Media",
    "description": "Plays media file",
    "command": "termux-media-player play [file]",
    "category": "Camera & Media",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-pause-media",
    "title": "Pause Media",
    "description": "Pauses playing media",
    "command": "termux-media-player pause",
    "category": "Camera & Media",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-stop-media",
    "title": "Stop Media",
    "description": "Stops media playback",
    "command": "termux-media-player stop",
    "category": "Camera & Media",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-seek-media",
    "title": "Seek Media",
    "description": "Seeks media to given time",
    "command": "termux-media-player seek [time]",
    "category": "Camera & Media",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-load-playlist",
    "title": "Load Playlist",
    "description": "Loads playlist from file",
    "command": "termux-media-player playlist [file]",
    "category": "Camera & Media",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-toggle-wi-fi",
    "title": "Toggle Wi-Fi",
    "description": "Enable or disable Wi-Fi",
    "command": "termux-wifi-enable [true/false]",
    "category": "Wi-Fi & Telephony",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-wi-fi-connection-info",
    "title": "Wi-Fi Connection Info",
    "description": "Show Wi-Fi connection info",
    "command": "termux-wifi-connectioninfo",
    "category": "Wi-Fi & Telephony",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-ip-info",
    "title": "IP Info",
    "description": "Display IP address info",
    "command": "termux-wifi-ipinfo",
    "category": "Wi-Fi & Telephony",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-scan-wi-fi",
    "title": "Scan Wi-Fi",
    "description": "Scan Wi-Fi networks",
    "command": "termux-wifi-scaninfo",
    "category": "Wi-Fi & Telephony",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-device-info",
    "title": "Device Info",
    "description": "Device SIM and network info",
    "command": "termux-telephony-deviceinfo",
    "category": "Wi-Fi & Telephony",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-signal-strength",
    "title": "Signal Strength",
    "description": "Signal strength info",
    "command": "termux-telephony-signalstrength",
    "category": "Wi-Fi & Telephony",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson1-device-imei",
    "title": "Device IMEI",
    "description": "Show device IMEI",
    "command": "termux-telephony-imei",
    "category": "Wi-Fi & Telephony",
    "lessonSlug": "/Lesson1",
    "lessonTitle": "Core Commands"
  },
  {
    "id": "lesson2-audio-info",
    "title": "Audio Info",
    "description": "Displays information about the audio system.",
    "command": "termux-audio-info",
    "category": "Audio & Microphone",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-play-audio",
    "title": "Play Audio",
    "description": "Plays the specified audio file.",
    "command": "termux-audio-play [file]",
    "category": "Audio & Microphone",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-record-audio",
    "title": "Record Audio",
    "description": "Records audio and saves it to the specified file.",
    "command": "termux-audio-record [output_file]",
    "category": "Audio & Microphone",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-record-mic",
    "title": "Record Mic",
    "description": "Records audio using the device's microphone.",
    "command": "termux-microphone-record [output_file]",
    "category": "Audio & Microphone",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-show-call-log",
    "title": "Show Call Log",
    "description": "Lists the call log.",
    "command": "termux-call-log",
    "category": "Call & SMS",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-call-log-by-type",
    "title": "Call Log by Type",
    "description": "Lists entries by type (incoming, outgoing, missed).",
    "command": "termux-call-log -t [type]",
    "category": "Call & SMS",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-limit-call-log",
    "title": "Limit Call Log",
    "description": "Limits the number of call log entries shown.",
    "command": "termux-call-log -l [limit]",
    "category": "Call & SMS",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-list-sms",
    "title": "List SMS",
    "description": "Lists all SMS messages.",
    "command": "termux-sms-list",
    "category": "Call & SMS",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-sms-inbox",
    "title": "SMS Inbox",
    "description": "Shows received messages.",
    "command": "termux-sms-inbox",
    "category": "Call & SMS",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-send-sms",
    "title": "Send SMS",
    "description": "Sends SMS to number.",
    "command": "termux-sms-send -n [number] [message]",
    "category": "Call & SMS",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-view-sms",
    "title": "View SMS",
    "description": "Displays specific message.",
    "command": "termux-sms-view [message_id]",
    "category": "Call & SMS",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-camera-info",
    "title": "Camera Info",
    "description": "Displays camera info.",
    "command": "termux-camera-info",
    "category": "Camera & Media",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-take-photo",
    "title": "Take Photo",
    "description": "Takes a photo and saves it.",
    "command": "termux-camera-photo [output_file]",
    "category": "Camera & Media",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-record-video",
    "title": "Record Video",
    "description": "Records a video and saves it.",
    "command": "termux-camera-record [output_file]",
    "category": "Camera & Media",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-snapshot",
    "title": "Snapshot",
    "description": "Takes a camera snapshot.",
    "command": "termux-camera-snapshot [output_file]",
    "category": "Camera & Media",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-camera-preview",
    "title": "Camera Preview",
    "description": "Opens a live camera preview.",
    "command": "termux-camera-view",
    "category": "Camera & Media",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-scan-media",
    "title": "Scan Media",
    "description": "Scans path for media.",
    "command": "termux-media-scan [path]",
    "category": "Camera & Media",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-get-clipboard",
    "title": "Get Clipboard",
    "description": "Retrieves clipboard contents.",
    "command": "termux-clipboard-get",
    "category": "Clipboard & Contacts",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-set-clipboard",
    "title": "Set Clipboard",
    "description": "Sets clipboard to specified text.",
    "command": "termux-clipboard-set [text]",
    "category": "Clipboard & Contacts",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-get-contact",
    "title": "Get Contact",
    "description": "Retrieves a contact's info.",
    "command": "termux-contact-get [contact_name]",
    "category": "Clipboard & Contacts",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-list-contacts",
    "title": "List Contacts",
    "description": "Lists all contacts.",
    "command": "termux-contact-list",
    "category": "Clipboard & Contacts",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-connect-wi-fi",
    "title": "Connect Wi-Fi",
    "description": "Connects to a Wi-Fi network.",
    "command": "termux-wifi-connect [SSID] [password]",
    "category": "Network & Connectivity",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-toggle-wi-fi",
    "title": "Toggle Wi-Fi",
    "description": "Enables or disables Wi-Fi.",
    "command": "termux-wifi-enable [true/false]",
    "category": "Network & Connectivity",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-wi-fi-ip-info",
    "title": "Wi-Fi IP Info",
    "description": "Displays IP address info.",
    "command": "termux-wifi-ipinfo",
    "category": "Network & Connectivity",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-wi-fi-scan",
    "title": "Wi-Fi Scan",
    "description": "Scans nearby networks.",
    "command": "termux-wifi-scaninfo",
    "category": "Network & Connectivity",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-cell-info",
    "title": "Cell Info",
    "description": "Shows cellular network info.",
    "command": "termux-telephony-cellinfo",
    "category": "Network & Connectivity",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-device-info",
    "title": "Device Info",
    "description": "Shows telephony device info.",
    "command": "termux-telephony-deviceinfo",
    "category": "Network & Connectivity",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-imei",
    "title": "IMEI",
    "description": "Displays device IMEI.",
    "command": "termux-telephony-imei",
    "category": "Network & Connectivity",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-signal-strength",
    "title": "Signal Strength",
    "description": "Shows signal strength.",
    "command": "termux-telephony-signalstrength",
    "category": "Network & Connectivity",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-download-file",
    "title": "Download File",
    "description": "Downloads a file from URL.",
    "command": "termux-download [URL]",
    "category": "Files & Editor",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-open-file-editor",
    "title": "Open File Editor",
    "description": "Opens a file in text editor.",
    "command": "termux-file-editor [file]",
    "category": "Files & Editor",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-open-editable-file",
    "title": "Open Editable File",
    "description": "Opens file in editable editor.",
    "command": "termux-file-editor-editable [file]",
    "category": "Files & Editor",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-fix-shebang",
    "title": "Fix Shebang",
    "description": "Fixes shebang to make script executable.",
    "command": "termux-fix-shebang [file]",
    "category": "Files & Editor",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-open-file",
    "title": "Open File",
    "description": "Opens file or dir.",
    "command": "termux-open [file/path]",
    "category": "Files & Editor",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-open-url",
    "title": "Open URL",
    "description": "Opens link in browser.",
    "command": "termux-open-url [URL]",
    "category": "Files & Editor",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-upload-file",
    "title": "Upload File",
    "description": "Uploads file to destination.",
    "command": "termux-upload [source_file] [destination_directory]",
    "category": "Files & Editor",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-send-notification",
    "title": "Send Notification",
    "description": "Sends a notification.",
    "command": "termux-notification",
    "category": "System & Notifications",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-list-tts-engines",
    "title": "List TTS Engines",
    "description": "Lists TTS engines.",
    "command": "termux-tts-engines",
    "category": "System & Notifications",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-speak-text",
    "title": "Speak Text",
    "description": "Speaks text aloud.",
    "command": "termux-tts-speak [text]",
    "category": "System & Notifications",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-volume-control",
    "title": "Volume Control",
    "description": "Controls system volume.",
    "command": "termux-volume",
    "category": "System & Notifications",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-flashlight",
    "title": "Flashlight",
    "description": "Turns flashlight on/off.",
    "command": "termux-torch [true/false]",
    "category": "System & Notifications",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-system-info",
    "title": "System Info",
    "description": "Displays system info.",
    "command": "termux-info",
    "category": "System & Notifications",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-broadcast-intent",
    "title": "Broadcast Intent",
    "description": "Sends a broadcast intent.",
    "command": "termux-am broadcast -a [action]",
    "category": "Advanced Features",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-ir-frequencies",
    "title": "IR Frequencies",
    "description": "Lists infrared frequencies.",
    "command": "termux-infrared-frequencies",
    "category": "Advanced Features",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-ir-transmit",
    "title": "IR Transmit",
    "description": "Transmits IR pattern.",
    "command": "termux-infrared-transmit [frequency] [pattern]",
    "category": "Advanced Features",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-keyring",
    "title": "Keyring",
    "description": "Manages secrets.",
    "command": "termux-keyring [options]",
    "category": "Advanced Features",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-share-content",
    "title": "Share Content",
    "description": "Shares via Android menu.",
    "command": "termux-share",
    "category": "Advanced Features",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-show-dialog",
    "title": "Show Dialog",
    "description": "Displays a dialog box.",
    "command": "termux-dialog",
    "category": "Advanced Features",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-open-with-app",
    "title": "Open with App",
    "description": "Opens link with default app.",
    "command": "termux-url-opener [URL]",
    "category": "Advanced Features",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson2-set-wallpaper",
    "title": "Set Wallpaper",
    "description": "Changes device wallpaper.",
    "command": "termux-wallpaper [file]",
    "category": "Advanced Features",
    "lessonSlug": "/Lesson2",
    "lessonTitle": "Intermediate Commands"
  },
  {
    "id": "lesson3-termux-api",
    "title": "Termux API",
    "description": "Access various Android APIs from Termux scripts.",
    "command": "termux-api",
    "category": "Core System",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-battery-status",
    "title": "Battery Status",
    "description": "Get battery status including level and health.",
    "command": "termux-battery-status",
    "category": "Core System",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-system-info",
    "title": "System Info",
    "description": "Display general system information.",
    "command": "termux-info",
    "category": "Core System",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-job-scheduler",
    "title": "Job Scheduler",
    "description": "Schedule background jobs.",
    "command": "termux-job-scheduler [options]",
    "category": "Core System",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-camera-info",
    "title": "Camera Info",
    "description": "Get information about available cameras.",
    "command": "termux-camera-info",
    "category": "Camera & Media",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-media-player",
    "title": "Media Player",
    "description": "Control audio/video media playback.",
    "command": "termux-media-player",
    "category": "Camera & Media",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-media-scan",
    "title": "Media Scan",
    "description": "Scan for media files at the specified path.",
    "command": "termux-media-scan [path]",
    "category": "Camera & Media",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-call-log",
    "title": "Call Log",
    "description": "View call logs (incoming/outgoing/missed).",
    "command": "termux-call-log",
    "category": "Telephony & SMS",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-cell-info",
    "title": "Cell Info",
    "description": "Cellular network cell info.",
    "command": "termux-telephony-cellinfo",
    "category": "Telephony & SMS",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-device-info",
    "title": "Device Info",
    "description": "Device and SIM card info.",
    "command": "termux-telephony-deviceinfo",
    "category": "Telephony & SMS",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-imei-number",
    "title": "IMEI Number",
    "description": "Show device IMEI number.",
    "command": "termux-telephony-imei",
    "category": "Telephony & SMS",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-signal-strength",
    "title": "Signal Strength",
    "description": "Get mobile network signal strength.",
    "command": "termux-telephony-signalstrength",
    "category": "Telephony & SMS",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-sms-inbox",
    "title": "SMS Inbox",
    "description": "List received SMS messages.",
    "command": "termux-sms-inbox",
    "category": "Telephony & SMS",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-send-sms",
    "title": "Send SMS",
    "description": "Send SMS to number.",
    "command": "termux-sms-send -n [number] [message]",
    "category": "Telephony & SMS",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-view-sms",
    "title": "View SMS",
    "description": "View details of an SMS message.",
    "command": "termux-sms-view [message_id]",
    "category": "Telephony & SMS",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-get-clipboard",
    "title": "Get Clipboard",
    "description": "Get current clipboard contents.",
    "command": "termux-clipboard-get",
    "category": "Clipboard & Contacts",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-set-clipboard",
    "title": "Set Clipboard",
    "description": "Set clipboard to specified text.",
    "command": "termux-clipboard-set [text]",
    "category": "Clipboard & Contacts",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-contact-list",
    "title": "Contact List",
    "description": "List all contacts from device.",
    "command": "termux-contact-list",
    "category": "Clipboard & Contacts",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-wi-fi-connect",
    "title": "Wi-Fi Connect",
    "description": "Connect to a Wi-Fi network.",
    "command": "termux-wifi-connect [SSID] [password]",
    "category": "Network & Connectivity",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-wi-fi-enable",
    "title": "Wi-Fi Enable",
    "description": "Enable or disable Wi-Fi.",
    "command": "termux-wifi-enable [true/false]",
    "category": "Network & Connectivity",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-wi-fi-ip-info",
    "title": "Wi-Fi IP Info",
    "description": "Get current IP address information.",
    "command": "termux-wifi-ipinfo",
    "category": "Network & Connectivity",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-wi-fi-scan",
    "title": "Wi-Fi Scan",
    "description": "Scan and display nearby Wi-Fi networks.",
    "command": "termux-wifi-scaninfo",
    "category": "Network & Connectivity",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-send-notification",
    "title": "Send Notification",
    "description": "Send a custom notification.",
    "command": "termux-notification",
    "category": "Notifications & Audio",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-list-notifications",
    "title": "List Notifications",
    "description": "List all active notifications.",
    "command": "termux-notification-list",
    "category": "Notifications & Audio",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-remove-notification",
    "title": "Remove Notification",
    "description": "Remove notification with specific ID.",
    "command": "termux-notification-remove [id]",
    "category": "Notifications & Audio",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-clear-notifications",
    "title": "Clear Notifications",
    "description": "Remove all active notifications.",
    "command": "termux-notification-remove-all",
    "category": "Notifications & Audio",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-text-to-speech",
    "title": "Text to Speech",
    "description": "Text-to-speech: speak text aloud.",
    "command": "termux-tts-speak [text]",
    "category": "Notifications & Audio",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-volume-control",
    "title": "Volume Control",
    "description": "Control volume level of device streams.",
    "command": "termux-volume",
    "category": "Notifications & Audio",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-download-file",
    "title": "Download File",
    "description": "Download file from specified URL.",
    "command": "termux-download [URL]",
    "category": "File & Content",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-open-file",
    "title": "Open File",
    "description": "Open file or directory with default app.",
    "command": "termux-open [file/path]",
    "category": "File & Content",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-open-url",
    "title": "Open URL",
    "description": "Open URL in browser.",
    "command": "termux-open-url [URL]",
    "category": "File & Content",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-url-opener",
    "title": "URL Opener",
    "description": "Open URL using default handler.",
    "command": "termux-url-opener [URL]",
    "category": "File & Content",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-share-content",
    "title": "Share Content",
    "description": "Share file or content via Android share menu.",
    "command": "termux-share",
    "category": "File & Content",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-set-wallpaper",
    "title": "Set Wallpaper",
    "description": "Set the wallpaper to the given image.",
    "command": "termux-wallpaper [file]",
    "category": "File & Content",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-get-location",
    "title": "Get Location",
    "description": "Get current device location using GPS/network.",
    "command": "termux-location",
    "category": "Advanced & Hardware",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-infrared-transmit",
    "title": "Infrared Transmit",
    "description": "Send IR signals.",
    "command": "termux-infrared-transmit [frequency] [pattern]",
    "category": "Advanced & Hardware",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson3-show-dialog",
    "title": "Show Dialog",
    "description": "Show custom interactive dialog boxes.",
    "command": "termux-dialog",
    "category": "Advanced & Hardware",
    "lessonSlug": "/Lesson3",
    "lessonTitle": "Advanced Commands"
  },
  {
    "id": "lesson4-access-apis",
    "title": "Access APIs",
    "description": "Allows access to various device APIs from Termux shell scripts.",
    "command": "termux-api",
    "category": "Core System & API",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-system-info",
    "title": "System Info",
    "description": "Displays system information.",
    "command": "termux-info",
    "category": "Core System & API",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-job-scheduler",
    "title": "Job Scheduler",
    "description": "Schedules jobs to run in the background.",
    "command": "termux-job-scheduler [options]",
    "category": "Core System & API",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-battery-status",
    "title": "Battery Status",
    "description": "Shows battery information such as level, status, health, etc.",
    "command": "termux-battery-status",
    "category": "Core System & API",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-volume-control",
    "title": "Volume Control",
    "description": "Controls volume settings.",
    "command": "termux-volume",
    "category": "Core System & API",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-camera-info",
    "title": "Camera Info",
    "description": "Provides information about the device's camera(s).",
    "command": "termux-camera-info",
    "category": "Camera & Media",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-media-player",
    "title": "Media Player",
    "description": "Controls media playback.",
    "command": "termux-media-player",
    "category": "Camera & Media",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-media-scan",
    "title": "Media Scan",
    "description": "Scans the specified path for media files.",
    "command": "termux-media-scan [path]",
    "category": "Camera & Media",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-clipboard-get",
    "title": "Clipboard Get",
    "description": "Retrieves the current contents of the clipboard.",
    "command": "termux-clipboard-get",
    "category": "Clipboard & Contacts",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-clipboard-set",
    "title": "Clipboard Set",
    "description": "Sets the clipboard contents to the specified text.",
    "command": "termux-clipboard-set [text]",
    "category": "Clipboard & Contacts",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-contact-list",
    "title": "Contact List",
    "description": "Lists all contacts stored on the device.",
    "command": "termux-contact-list",
    "category": "Clipboard & Contacts",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-view-sms-inbox",
    "title": "View SMS Inbox",
    "description": "Lists received SMS messages.",
    "command": "termux-sms-inbox",
    "category": "Telephony & SMS",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-send-sms",
    "title": "Send SMS",
    "description": "Sends an SMS to the specified number with the given message.",
    "command": "termux-sms-send -n [number] [message]",
    "category": "Telephony & SMS",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-view-sms",
    "title": "View SMS",
    "description": "Displays the contents of the specified SMS message.",
    "command": "termux-sms-view [message_id]",
    "category": "Telephony & SMS",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-cell-info",
    "title": "Cell Info",
    "description": "Shows information about the current cellular network.",
    "command": "termux-telephony-cellinfo",
    "category": "Telephony & SMS",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-device-info",
    "title": "Device Info",
    "description": "Shows device-specific information.",
    "command": "termux-telephony-deviceinfo",
    "category": "Telephony & SMS",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-imei",
    "title": "IMEI",
    "description": "Shows the IMEI number of the device.",
    "command": "termux-telephony-imei",
    "category": "Telephony & SMS",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-signal-strength",
    "title": "Signal Strength",
    "description": "Shows signal strength information.",
    "command": "termux-telephony-signalstrength",
    "category": "Telephony & SMS",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-connect-to-wi-fi",
    "title": "Connect to Wi-Fi",
    "description": "Connects to the specified Wi-Fi network.",
    "command": "termux-wifi-connect [SSID] [password]",
    "category": "Network & Connectivity",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-enable-disable-wi-fi",
    "title": "Enable/Disable Wi-Fi",
    "description": "Enables or disables Wi-Fi.",
    "command": "termux-wifi-enable [true/false]",
    "category": "Network & Connectivity",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-wi-fi-ip-info",
    "title": "Wi-Fi IP Info",
    "description": "Displays information about the device's IP address.",
    "command": "termux-wifi-ipinfo",
    "category": "Network & Connectivity",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-wi-fi-scan-info",
    "title": "Wi-Fi Scan Info",
    "description": "Scans for Wi-Fi networks and displays information about them.",
    "command": "termux-wifi-scaninfo",
    "category": "Network & Connectivity",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-send-notification",
    "title": "Send Notification",
    "description": "Sends a notification to the notification bar.",
    "command": "termux-notification",
    "category": "Notifications & Audio",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-remove-notification",
    "title": "Remove Notification",
    "description": "Removes a notification with the specified ID.",
    "command": "termux-notification-remove [id]",
    "category": "Notifications & Audio",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-list-notifications",
    "title": "List Notifications",
    "description": "Lists all active notifications.",
    "command": "termux-notification-list",
    "category": "Notifications & Audio",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-remove-all-notifications",
    "title": "Remove All Notifications",
    "description": "Removes all active notifications.",
    "command": "termux-notification-remove-all",
    "category": "Notifications & Audio",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-text-to-speech",
    "title": "Text to Speech",
    "description": "Converts text to speech and speaks it aloud.",
    "command": "termux-tts-speak [text]",
    "category": "Notifications & Audio",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-download-file",
    "title": "Download File",
    "description": "Downloads a file from the specified URL.",
    "command": "termux-download [URL]",
    "category": "File & Content",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-open-url",
    "title": "Open URL",
    "description": "Opens the specified URL in the default app.",
    "command": "termux-url-opener [URL]",
    "category": "File & Content",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-open-in-browser",
    "title": "Open in Browser",
    "description": "Opens the specified URL in the default browser.",
    "command": "termux-open-url [URL]",
    "category": "File & Content",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-open-file-path",
    "title": "Open File/Path",
    "description": "Opens a file or directory with the default app.",
    "command": "termux-open [file/path]",
    "category": "File & Content",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-share-content",
    "title": "Share Content",
    "description": "Shares files or text using the Android share menu.",
    "command": "termux-share",
    "category": "File & Content",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-set-wallpaper",
    "title": "Set Wallpaper",
    "description": "Sets the device's wallpaper to the specified image file.",
    "command": "termux-wallpaper [file]",
    "category": "File & Content",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-location",
    "title": "Location",
    "description": "Retrieves the device's current location.",
    "command": "termux-location",
    "category": "Advanced & Hardware",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-infrared-transmit",
    "title": "Infrared Transmit",
    "description": "Transmits an infrared pattern at the specified frequency.",
    "command": "termux-infrared-transmit [frequency] [pattern]",
    "category": "Advanced & Hardware",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson4-dialog-box",
    "title": "Dialog Box",
    "description": "Displays a customizable dialog box.",
    "command": "termux-dialog",
    "category": "Advanced & Hardware",
    "lessonSlug": "/Lesson4",
    "lessonTitle": "Expert Commands"
  },
  {
    "id": "lesson5-activity-manager",
    "title": "Activity Manager",
    "description": "Manages activities running in the background.",
    "command": "termux-activity-manager",
    "category": "App & Activity",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-app-info",
    "title": "App Info",
    "description": "Displays information about the specified app.",
    "command": "termux-app-info [package_name]",
    "category": "App & Activity",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-app-list",
    "title": "App List",
    "description": "Lists all installed apps.",
    "command": "termux-app-list",
    "category": "App & Activity",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-audio-info",
    "title": "Audio Info",
    "description": "Displays information about the audio system.",
    "command": "termux-audio-info",
    "category": "Audio",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-play-audio",
    "title": "Play Audio",
    "description": "Plays the specified audio file.",
    "command": "termux-audio-play [file]",
    "category": "Audio",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-record-audio",
    "title": "Record Audio",
    "description": "Records audio and saves it to the specified file.",
    "command": "termux-audio-record [output_file]",
    "category": "Audio",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-record-microphone",
    "title": "Record Microphone",
    "description": "Records audio using the microphone.",
    "command": "termux-microphone-record [output_file]",
    "category": "Audio",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-battery-status",
    "title": "Battery Status",
    "description": "Shows battery information.",
    "command": "termux-battery-status",
    "category": "System & Display",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-brightness-control",
    "title": "Brightness Control",
    "description": "Sets screen brightness.",
    "command": "termux-brightness [value]",
    "category": "System & Display",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-camera-info",
    "title": "Camera Info",
    "description": "Provides camera information.",
    "command": "termux-camera-info",
    "category": "Camera",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-take-photo",
    "title": "Take Photo",
    "description": "Takes a photo.",
    "command": "termux-camera-photo [output_file]",
    "category": "Camera",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-record-video",
    "title": "Record Video",
    "description": "Records a video.",
    "command": "termux-camera-record [output_file]",
    "category": "Camera",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-camera-snapshot",
    "title": "Camera Snapshot",
    "description": "Takes a snapshot.",
    "command": "termux-camera-snapshot [output_file]",
    "category": "Camera",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-camera-preview",
    "title": "Camera Preview",
    "description": "Opens a live camera preview.",
    "command": "termux-camera-view",
    "category": "Camera",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-get-clipboard",
    "title": "Get Clipboard",
    "description": "Gets clipboard contents.",
    "command": "termux-clipboard-get",
    "category": "Clipboard & Contacts",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-set-clipboard",
    "title": "Set Clipboard",
    "description": "Sets clipboard contents.",
    "command": "termux-clipboard-set [text]",
    "category": "Clipboard & Contacts",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-clear-clipboard",
    "title": "Clear Clipboard",
    "description": "Clears clipboard.",
    "command": "termux-clipboard-clear",
    "category": "Clipboard & Contacts",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-get-contact",
    "title": "Get Contact",
    "description": "Gets contact info.",
    "command": "termux-contact-get [contact_name]",
    "category": "Clipboard & Contacts",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-list-contacts",
    "title": "List Contacts",
    "description": "Lists all contacts.",
    "command": "termux-contact-list",
    "category": "Clipboard & Contacts",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-ir-frequencies",
    "title": "IR Frequencies",
    "description": "Lists IR frequencies.",
    "command": "termux-infrared-frequencies",
    "category": "Infrared & Storage",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-ir-transmit",
    "title": "IR Transmit",
    "description": "Sends IR pattern.",
    "command": "termux-infrared-transmit [frequency] [pattern]",
    "category": "Infrared & Storage",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-storage-list",
    "title": "Storage List",
    "description": "Lists storage volumes.",
    "command": "termux-storage-list",
    "category": "Infrared & Storage",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-storage-info",
    "title": "Storage Info",
    "description": "Gets storage path info.",
    "command": "termux-storage-get [path]",
    "category": "Infrared & Storage",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-download-file",
    "title": "Download File",
    "description": "Downloads a file.",
    "command": "termux-download [URL]",
    "category": "Utilities",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-system-info",
    "title": "System Info",
    "description": "Shows system info.",
    "command": "termux-info",
    "category": "Utilities",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-fix-shebang",
    "title": "Fix Shebang",
    "description": "Fixes script shebang.",
    "command": "termux-fix-shebang [file]",
    "category": "Utilities",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-set-wallpaper",
    "title": "Set Wallpaper",
    "description": "Sets wallpaper.",
    "command": "termux-wallpaper [file]",
    "category": "Utilities",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-flashlight",
    "title": "Flashlight",
    "description": "Toggles flashlight.",
    "command": "termux-torch [true/false]",
    "category": "Utilities",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-volume-control",
    "title": "Volume Control",
    "description": "Controls volume.",
    "command": "termux-volume",
    "category": "Utilities",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-open-url",
    "title": "Open URL",
    "description": "Opens URL in browser.",
    "command": "termux-open-url [URL]",
    "category": "Utilities",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-open-file",
    "title": "Open File",
    "description": "Opens file/path.",
    "command": "termux-open [file/path]",
    "category": "Utilities",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-keyring-manager",
    "title": "Keyring Manager",
    "description": "Manages secrets.",
    "command": "termux-keyring [options]",
    "category": "Utilities",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson5-upload-file",
    "title": "Upload File",
    "description": "Uploads file.",
    "command": "termux-upload [source_file] [destination_directory]",
    "category": "Utilities",
    "lessonSlug": "/Lesson5",
    "lessonTitle": "Power User Commands"
  },
  {
    "id": "lesson6-get-clipboard-text",
    "title": "Get Clipboard Text",
    "description": "Retrieves the current contents of the clipboard.",
    "command": "termux-clipboard-get",
    "category": "Clipboard & Sharing",
    "lessonSlug": "/Lesson6",
    "lessonTitle": "Developer Commands"
  },
  {
    "id": "lesson6-set-clipboard-text",
    "title": "Set Clipboard Text",
    "description": "Sets the clipboard contents to the specified text.",
    "command": "termux-clipboard-set 'Hello from Termux!'",
    "category": "Clipboard & Sharing",
    "lessonSlug": "/Lesson6",
    "lessonTitle": "Developer Commands"
  },
  {
    "id": "lesson6-share-content",
    "title": "Share Content",
    "description": "Shares files or text using the Android share menu.",
    "command": "termux-share -a send -c 'Check this out!'",
    "category": "Clipboard & Sharing",
    "lessonSlug": "/Lesson6",
    "lessonTitle": "Developer Commands"
  },
  {
    "id": "lesson6-system-info",
    "title": "System Info",
    "description": "Displays Termux environment debug information.",
    "command": "termux-info",
    "category": "Device Info",
    "lessonSlug": "/Lesson6",
    "lessonTitle": "Developer Commands"
  },
  {
    "id": "lesson6-cpu-info",
    "title": "CPU Info",
    "description": "Displays information about the device's CPU.",
    "command": "termux-cpu-info",
    "category": "Device Info",
    "lessonSlug": "/Lesson6",
    "lessonTitle": "Developer Commands"
  },
  {
    "id": "lesson6-get-location",
    "title": "Get Location",
    "description": "Retrieves the device's current GPS location.",
    "command": "termux-location",
    "category": "Device Info",
    "lessonSlug": "/Lesson6",
    "lessonTitle": "Developer Commands"
  },
  {
    "id": "lesson6-camera-photo",
    "title": "Camera Photo",
    "description": "Takes a photo using the device's camera.",
    "command": "termux-camera-photo -c 0 photo.jpg",
    "category": "Media & Camera",
    "lessonSlug": "/Lesson6",
    "lessonTitle": "Developer Commands"
  },
  {
    "id": "lesson6-play-media",
    "title": "Play Media",
    "description": "Plays an audio file using Termux's media player.",
    "command": "termux-media-player play file.mp3",
    "category": "Media & Camera",
    "lessonSlug": "/Lesson6",
    "lessonTitle": "Developer Commands"
  },
  {
    "id": "lesson6-send-notification",
    "title": "Send Notification",
    "description": "Sends a notification to the Android system tray.",
    "command": "termux-notification -t 'Hi' -c 'This is from Termux'",
    "category": "Notifications",
    "lessonSlug": "/Lesson6",
    "lessonTitle": "Developer Commands"
  },
  {
    "id": "lesson6-remove-notification",
    "title": "Remove Notification",
    "description": "Removes a previously sent notification.",
    "command": "termux-notification-remove 1",
    "category": "Notifications",
    "lessonSlug": "/Lesson6",
    "lessonTitle": "Developer Commands"
  },
  {
    "id": "lesson6-scan-wi-fi",
    "title": "Scan Wi-Fi",
    "description": "Scans and displays nearby Wi-Fi networks.",
    "command": "termux-wifi-scaninfo",
    "category": "Network & Web",
    "lessonSlug": "/Lesson6",
    "lessonTitle": "Developer Commands"
  },
  {
    "id": "lesson6-open-url",
    "title": "Open URL",
    "description": "Opens a URL in the device's default browser.",
    "command": "termux-open-url https://example.com",
    "category": "Network & Web",
    "lessonSlug": "/Lesson6",
    "lessonTitle": "Developer Commands"
  },
  {
    "id": "lesson6-send-sms",
    "title": "Send SMS",
    "description": "Sends an SMS message to a phone number.",
    "command": "termux-sms-send -n 1234567890 'Hello!'",
    "category": "Telephony",
    "lessonSlug": "/Lesson6",
    "lessonTitle": "Developer Commands"
  },
  {
    "id": "lesson6-get-call-log",
    "title": "Get Call Log",
    "description": "Lists recent call history from the device.",
    "command": "termux-call-log",
    "category": "Telephony",
    "lessonSlug": "/Lesson6",
    "lessonTitle": "Developer Commands"
  },
  {
    "id": "lesson6-access-contact-list",
    "title": "Access Contact List",
    "description": "Lists all saved contacts.",
    "command": "termux-contact-list",
    "category": "Contacts",
    "lessonSlug": "/Lesson6",
    "lessonTitle": "Developer Commands"
  },
  {
    "id": "lesson7-termux-add-repo-repository",
    "title": "termux-add-repo [repository]",
    "description": "Adds a new repository to the list of available repositories.",
    "command": "termux-add-repo [repository]",
    "category": "Repository & Packages",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-create-package-package-name",
    "title": "termux-create-package [package_name]",
    "description": "Creates a new package with the specified name.",
    "command": "termux-create-package [package_name]",
    "category": "Repository & Packages",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-package-info-package-name",
    "title": "termux-package-info [package_name]",
    "description": "Displays information about the specified package.",
    "command": "termux-package-info [package_name]",
    "category": "Repository & Packages",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-package-list-options",
    "title": "termux-package-list [options]",
    "description": "Lists installed packages.",
    "command": "termux-package-list [options]",
    "category": "Repository & Packages",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-fix-permissions-directory-file",
    "title": "termux-fix-permissions [directory/file]",
    "description": "Fixes permissions for the specified directory or file.",
    "command": "termux-fix-permissions [directory/file]",
    "category": "Security & Permissions",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-fix-shebang-file",
    "title": "termux-fix-shebang [file]",
    "description": "Fixes the shebang of a script file to make it executable.",
    "command": "termux-fix-shebang [file]",
    "category": "Security & Permissions",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-fingerprint-options",
    "title": "termux-fingerprint [options]",
    "description": "Manages fingerprints for SSH connections.",
    "command": "termux-fingerprint [options]",
    "category": "Security & Permissions",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-lock-settings",
    "title": "termux-lock-settings",
    "description": "Locks Termux settings with a password.",
    "command": "termux-lock-settings",
    "category": "Security & Permissions",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-sudo",
    "title": "termux-sudo",
    "description": "Runs a command with superuser privileges.",
    "command": "termux-sudo",
    "category": "Security & Permissions",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-chroot-directory",
    "title": "termux-chroot [directory]",
    "description": "Changes the root directory for the current session.",
    "command": "termux-chroot [directory]",
    "category": "Configuration",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-info",
    "title": "termux-info",
    "description": "Displays system information.",
    "command": "termux-info",
    "category": "Configuration",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-reload-settings",
    "title": "termux-reload-settings",
    "description": "Reloads Termux settings from disk.",
    "command": "termux-reload-settings",
    "category": "Configuration",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-reload-style",
    "title": "termux-reload-style",
    "description": "Reloads the Termux console style settings.",
    "command": "termux-reload-style",
    "category": "Configuration",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-reload-fonts",
    "title": "termux-reload-fonts",
    "description": "Reloads the Termux console font settings.",
    "command": "termux-reload-fonts",
    "category": "Configuration",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-reload-properties",
    "title": "termux-reload-properties",
    "description": "Reloads the Termux console properties settings.",
    "command": "termux-reload-properties",
    "category": "Configuration",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-reset-settings",
    "title": "termux-reset-settings",
    "description": "Resets Termux settings to default values.",
    "command": "termux-reset-settings",
    "category": "Configuration",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-reset",
    "title": "termux-reset",
    "description": "Resets Termux to a clean state.",
    "command": "termux-reset",
    "category": "Configuration",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-wifi-connect-ssid-password",
    "title": "termux-wifi-connect [SSID] [password]",
    "description": "Connects to the specified Wi-Fi network.",
    "command": "termux-wifi-connect [SSID] [password]",
    "category": "Network & Connectivity",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-wifi-enable-true-false",
    "title": "termux-wifi-enable [true/false]",
    "description": "Enables or disables Wi-Fi.",
    "command": "termux-wifi-enable [true/false]",
    "category": "Network & Connectivity",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-wifi-ipinfo",
    "title": "termux-wifi-ipinfo",
    "description": "Displays information about the device's IP address.",
    "command": "termux-wifi-ipinfo",
    "category": "Network & Connectivity",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-wifi-scaninfo",
    "title": "termux-wifi-scaninfo",
    "description": "Scans for Wi-Fi networks and displays information about them.",
    "command": "termux-wifi-scaninfo",
    "category": "Network & Connectivity",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-wifi-tether",
    "title": "termux-wifi-tether",
    "description": "Tethers the device's Wi-Fi connection.",
    "command": "termux-wifi-tether",
    "category": "Network & Connectivity",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-wifi-toggle",
    "title": "termux-wifi-toggle",
    "description": "Toggles the Wi-Fi connection.",
    "command": "termux-wifi-toggle",
    "category": "Network & Connectivity",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-wifi-connectioninfo",
    "title": "termux-wifi-connectioninfo",
    "description": "Shows information about the current Wi-Fi connection.",
    "command": "termux-wifi-connectioninfo",
    "category": "Network & Connectivity",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-setup-storage",
    "title": "termux-setup-storage",
    "description": "Sets up storage for Termux.",
    "command": "termux-setup-storage",
    "category": "Storage & Files",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-tmpdir",
    "title": "termux-tmpdir",
    "description": "Prints the path to the temporary directory.",
    "command": "termux-tmpdir",
    "category": "Storage & Files",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-open-file-path",
    "title": "termux-open [file/path]",
    "description": "Opens a file or directory with the default app.",
    "command": "termux-open [file/path]",
    "category": "Storage & Files",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-open-url-url",
    "title": "termux-open-url [URL]",
    "description": "Opens the specified URL in the default browser.",
    "command": "termux-open-url [URL]",
    "category": "Storage & Files",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-notify",
    "title": "termux-notify",
    "description": "Sends a notification to the notification bar.",
    "command": "termux-notify",
    "category": "Notifications & System",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-share",
    "title": "termux-share",
    "description": "Shares files or text using the Android share menu.",
    "command": "termux-share",
    "category": "Notifications & System",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-wallpaper-file",
    "title": "termux-wallpaper [file]",
    "description": "Sets the device's wallpaper to the specified image file.",
    "command": "termux-wallpaper [file]",
    "category": "Notifications & System",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-wake-lock",
    "title": "termux-wake-lock",
    "description": "Keeps the device awake until explicitly released.",
    "command": "termux-wake-lock",
    "category": "Notifications & System",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-wake-unlock",
    "title": "termux-wake-unlock",
    "description": "Releases the wake lock on the device.",
    "command": "termux-wake-unlock",
    "category": "Notifications & System",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson7-termux-telephony-configure",
    "title": "termux-telephony-configure",
    "description": "Configures telephony settings.",
    "command": "termux-telephony-configure",
    "category": "Notifications & System",
    "lessonSlug": "/Lesson7",
    "lessonTitle": "System Administration"
  },
  {
    "id": "lesson8-termux-ping",
    "title": "termux-ping",
    "description": "Sends ICMP echo requests to a host.",
    "command": "termux-ping",
    "category": "Basic Networking",
    "lessonSlug": "/Lesson8",
    "lessonTitle": "Network Administration"
  },
  {
    "id": "lesson8-termux-nping",
    "title": "termux-nping",
    "description": "Sends ICMP echo requests to a host.",
    "command": "termux-nping",
    "category": "Basic Networking",
    "lessonSlug": "/Lesson8",
    "lessonTitle": "Network Administration"
  },
  {
    "id": "lesson8-termux-traceroute",
    "title": "termux-traceroute",
    "description": "Traces the route taken by packets to a destination.",
    "command": "termux-traceroute",
    "category": "Basic Networking",
    "lessonSlug": "/Lesson8",
    "lessonTitle": "Network Administration"
  },
  {
    "id": "lesson8-termux-dns-lookup",
    "title": "termux-dns-lookup",
    "description": "Performs DNS lookups.",
    "command": "termux-dns-lookup",
    "category": "Basic Networking",
    "lessonSlug": "/Lesson8",
    "lessonTitle": "Network Administration"
  },
  {
    "id": "lesson8-termux-whois",
    "title": "termux-whois",
    "description": "Retrieves WHOIS information for a domain.",
    "command": "termux-whois",
    "category": "Basic Networking",
    "lessonSlug": "/Lesson8",
    "lessonTitle": "Network Administration"
  },
  {
    "id": "lesson8-termux-ifconfig",
    "title": "termux-ifconfig",
    "description": "Displays or configures network interfaces.",
    "command": "termux-ifconfig",
    "category": "Network Config",
    "lessonSlug": "/Lesson8",
    "lessonTitle": "Network Administration"
  },
  {
    "id": "lesson8-termux-ip",
    "title": "termux-ip",
    "description": "Displays or configures network interfaces.",
    "command": "termux-ip",
    "category": "Network Config",
    "lessonSlug": "/Lesson8",
    "lessonTitle": "Network Administration"
  },
  {
    "id": "lesson8-termux-hostname",
    "title": "termux-hostname",
    "description": "Displays or sets the system hostname.",
    "command": "termux-hostname",
    "category": "Network Config",
    "lessonSlug": "/Lesson8",
    "lessonTitle": "Network Administration"
  },
  {
    "id": "lesson8-termux-route",
    "title": "termux-route",
    "description": "Displays or modifies the IP routing table.",
    "command": "termux-route",
    "category": "Network Config",
    "lessonSlug": "/Lesson8",
    "lessonTitle": "Network Administration"
  },
  {
    "id": "lesson8-termux-arp",
    "title": "termux-arp",
    "description": "Displays and modifies the ARP cache.",
    "command": "termux-arp",
    "category": "Network Config",
    "lessonSlug": "/Lesson8",
    "lessonTitle": "Network Administration"
  },
  {
    "id": "lesson8-termux-netstat",
    "title": "termux-netstat",
    "description": "Displays network connections, routing tables, etc.",
    "command": "termux-netstat",
    "category": "Network Monitoring",
    "lessonSlug": "/Lesson8",
    "lessonTitle": "Network Administration"
  },
  {
    "id": "lesson8-termux-ss",
    "title": "termux-ss",
    "description": "Displays socket statistics.",
    "command": "termux-ss",
    "category": "Network Monitoring",
    "lessonSlug": "/Lesson8",
    "lessonTitle": "Network Administration"
  },
  {
    "id": "lesson8-termux-iostat",
    "title": "termux-iostat",
    "description": "Displays I/O statistics.",
    "command": "termux-iostat",
    "category": "Network Monitoring",
    "lessonSlug": "/Lesson8",
    "lessonTitle": "Network Administration"
  },
  {
    "id": "lesson8-termux-df",
    "title": "termux-df",
    "description": "Displays disk usage statistics.",
    "command": "termux-df",
    "category": "Network Monitoring",
    "lessonSlug": "/Lesson8",
    "lessonTitle": "Network Administration"
  },
  {
    "id": "lesson8-termux-tcpdump",
    "title": "termux-tcpdump",
    "description": "Captures and analyzes network packets.",
    "command": "termux-tcpdump",
    "category": "Network Monitoring",
    "lessonSlug": "/Lesson8",
    "lessonTitle": "Network Administration"
  },
  {
    "id": "lesson8-termux-nmap",
    "title": "termux-nmap",
    "description": "Performs network discovery and security auditing.",
    "command": "termux-nmap",
    "category": "Security & Scanning",
    "lessonSlug": "/Lesson8",
    "lessonTitle": "Network Administration"
  },
  {
    "id": "lesson8-termux-sysctl",
    "title": "termux-sysctl",
    "description": "Configures kernel parameters at runtime.",
    "command": "termux-sysctl",
    "category": "Security & Scanning",
    "lessonSlug": "/Lesson8",
    "lessonTitle": "Network Administration"
  },
  {
    "id": "lesson8-termux-cpulimit",
    "title": "termux-cpulimit",
    "description": "Limits CPU usage of a process.",
    "command": "termux-cpulimit",
    "category": "Security & Scanning",
    "lessonSlug": "/Lesson8",
    "lessonTitle": "Network Administration"
  },
  {
    "id": "lesson8-termux-ssh",
    "title": "termux-ssh",
    "description": "Initiates an SSH session.",
    "command": "termux-ssh",
    "category": "Remote Access",
    "lessonSlug": "/Lesson8",
    "lessonTitle": "Network Administration"
  },
  {
    "id": "lesson8-termux-sshfs",
    "title": "termux-sshfs",
    "description": "Mounts a remote filesystem over SSH.",
    "command": "termux-sshfs",
    "category": "Remote Access",
    "lessonSlug": "/Lesson8",
    "lessonTitle": "Network Administration"
  },
  {
    "id": "lesson8-termux-telnet",
    "title": "termux-telnet",
    "description": "Initiates a Telnet session.",
    "command": "termux-telnet",
    "category": "Remote Access",
    "lessonSlug": "/Lesson8",
    "lessonTitle": "Network Administration"
  },
  {
    "id": "lesson8-termux-ftp",
    "title": "termux-ftp",
    "description": "Initiates an FTP session.",
    "command": "termux-ftp",
    "category": "Remote Access",
    "lessonSlug": "/Lesson8",
    "lessonTitle": "Network Administration"
  },
  {
    "id": "lesson8-termux-wget",
    "title": "termux-wget",
    "description": "Retrieves files from the web using HTTP, HTTPS, or FTP.",
    "command": "termux-wget",
    "category": "Remote Access",
    "lessonSlug": "/Lesson8",
    "lessonTitle": "Network Administration"
  },
  {
    "id": "lesson9-termux-cat-file",
    "title": "termux-cat [file]",
    "description": "Displays the contents of a file.",
    "command": "termux-cat [file]",
    "category": "File Viewing",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-head-options-file",
    "title": "termux-head [options] [file]",
    "description": "Displays the first part of a file.",
    "command": "termux-head [options] [file]",
    "category": "File Viewing",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-tail-options-file",
    "title": "termux-tail [options] [file]",
    "description": "Displays the last part of a file.",
    "command": "termux-tail [options] [file]",
    "category": "File Viewing",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-less-file",
    "title": "termux-less [file]",
    "description": "Displays the contents of a file, one screen at a time.",
    "command": "termux-less [file]",
    "category": "File Viewing",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-od-options-file",
    "title": "termux-od [options] [file]",
    "description": "Displays the contents of a file in various formats.",
    "command": "termux-od [options] [file]",
    "category": "File Viewing",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-tac-file",
    "title": "termux-tac [file]",
    "description": "Concatenates and prints files in reverse.",
    "command": "termux-tac [file]",
    "category": "File Viewing",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-ls-options",
    "title": "termux-ls [options]",
    "description": "Lists directory contents.",
    "command": "termux-ls [options]",
    "category": "File & Directory",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-pwd",
    "title": "termux-pwd",
    "description": "Prints the current working directory.",
    "command": "termux-pwd",
    "category": "File & Directory",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-mkdir-directory",
    "title": "termux-mkdir [directory]",
    "description": "Creates directories.",
    "command": "termux-mkdir [directory]",
    "category": "File & Directory",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-cp-source-destination",
    "title": "termux-cp [source] [destination]",
    "description": "Copies files and directories.",
    "command": "termux-cp [source] [destination]",
    "category": "File & Directory",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-mv-source-destination",
    "title": "termux-mv [source] [destination]",
    "description": "Moves or renames files and directories.",
    "command": "termux-mv [source] [destination]",
    "category": "File & Directory",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-rm-options-file",
    "title": "termux-rm [options] [file]",
    "description": "Removes files or directories.",
    "command": "termux-rm [options] [file]",
    "category": "File & Directory",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-ln-options-source-destination",
    "title": "termux-ln [options] [source] [destination]",
    "description": "Creates links to files.",
    "command": "termux-ln [options] [source] [destination]",
    "category": "File & Directory",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-touch-options-file",
    "title": "termux-touch [options] [file]",
    "description": "Updates the access and modification times of files.",
    "command": "termux-touch [options] [file]",
    "category": "File & Directory",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-stat-file",
    "title": "termux-stat [file]",
    "description": "Displays file or file system status.",
    "command": "termux-stat [file]",
    "category": "File Info",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-file-info-file",
    "title": "termux-file-info [file]",
    "description": "Displays information about a file.",
    "command": "termux-file-info [file]",
    "category": "File Info",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-realpath-file",
    "title": "termux-realpath [file]",
    "description": "Displays the absolute path of a file.",
    "command": "termux-realpath [file]",
    "category": "File Info",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-readlink-options-file",
    "title": "termux-readlink [options] [file]",
    "description": "Displays the value of a symbolic link.",
    "command": "termux-readlink [options] [file]",
    "category": "File Info",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-which-command",
    "title": "termux-which [command]",
    "description": "Locates the executable file associated with a given command.",
    "command": "termux-which [command]",
    "category": "File Info",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-md5sum-file",
    "title": "termux-md5sum [file]",
    "description": "Calculates and verifies MD5 checksums.",
    "command": "termux-md5sum [file]",
    "category": "File Info",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-sum-file",
    "title": "termux-sum [file]",
    "description": "Calculates checksums and counts the number of blocks for a file.",
    "command": "termux-sum [file]",
    "category": "File Info",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-cut-options",
    "title": "termux-cut [options]",
    "description": "Cuts out selected portions of each line of a file.",
    "command": "termux-cut [options]",
    "category": "Text Processing",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-paste",
    "title": "termux-paste",
    "description": "Combines lines from multiple files.",
    "command": "termux-paste",
    "category": "Text Processing",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-sort-options",
    "title": "termux-sort [options]",
    "description": "Sorts lines of text files.",
    "command": "termux-sort [options]",
    "category": "Text Processing",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-uniq-options",
    "title": "termux-uniq [options]",
    "description": "Reports or omits repeated lines.",
    "command": "termux-uniq [options]",
    "category": "Text Processing",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-wc-options-file",
    "title": "termux-wc [options] [file]",
    "description": "Prints newline, word, and byte counts for each file.",
    "command": "termux-wc [options] [file]",
    "category": "Text Processing",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-echo-text",
    "title": "termux-echo [text]",
    "description": "Displays a line of text.",
    "command": "termux-echo [text]",
    "category": "Text Processing",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-split-options-file",
    "title": "termux-split [options] [file]",
    "description": "Splits a file into pieces.",
    "command": "termux-split [options] [file]",
    "category": "File Operations",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-truncate-options-file",
    "title": "termux-truncate [options] [file]",
    "description": "Shrink or extend the size of a file.",
    "command": "termux-truncate [options] [file]",
    "category": "File Operations",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-sync",
    "title": "termux-sync",
    "description": "Synchronizes cached writes to persistent storage.",
    "command": "termux-sync",
    "category": "File Operations",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-xargs-options",
    "title": "termux-xargs [options]",
    "description": "Builds and executes command lines from standard input.",
    "command": "termux-xargs [options]",
    "category": "File Operations",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-whoami",
    "title": "termux-whoami",
    "description": "Displays the username of the current user.",
    "command": "termux-whoami",
    "category": "System Info",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  },
  {
    "id": "lesson9-termux-file-editor-file",
    "title": "termux-file-editor [file]",
    "description": "Opens a file in the default text editor.",
    "command": "termux-file-editor [file]",
    "category": "System Info",
    "lessonSlug": "/Lesson9",
    "lessonTitle": "Data Management"
  }
];
